# .render.yaml at the root of SOCAPP

services:
  # === Backend (FastAPI) ===
  - type: web
    name: socapp-backend
    runtime: python
    plan: free
    rootDir: .                         # Run from repo root
    buildCommand: pip install -r requirements.txt --only-binary=all
    startCommand: uvicorn backendsoc.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        sync: false
      - key: AURA_INSTANCEID
        sync: false
      - key: AURA_INSTANCENAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false

  # === Frontend (React / Vite) ===
  - type: web
    name: socapp-frontend
    runtime: node
    plan: free
    rootDir: hays                        # Frontend folder
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        sync: false
