services:
  - type: web
    name: socapp-backend
    runtime: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt --only-binary=:all:
    startCommand: uvicorn backendsoc.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - "NEO4J_URI="
      - "NEO4J_USER="
      - "NEO4J_PASSWORD="
      - "NEO4J_DATABASE="
      - "AURA_INSTANCEID="
      - "AURA_INSTANCENAME="
      - "JWT_SECRET_KEY="
      - "JWT_ALGORITHM="
      - "ACCESS_TOKEN_EXPIRE_MINUTES="

  - type: web
    name: socapp-frontend
    runtime: node
    plan: free
    rootDir: hays
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - "VITE_API_URL="
